Repository coala/gci-leaders, pull requests merged in 2018-09, with the labels that each got.

#152 rss.js: Fix TypeError for undefined oldData
  lib/rss.js
  tests/__data__/data_alt.json
  tests/__data__/feed_alt.xml
  tests/__data__/feed_items_alt.json
  tests/lib/rss.test.js
Labels: process/wip

#110 Create a README.md
  README.md
Labels: difficulty/newcomer, process/pending review, size/XS

#133 scrape.js: Deleted duplicated API call
  lib/scrape.js
Labels: difficulty/newcomer, initiatives/gci, process/pending review, size/XS

#149 .travis.yml: Enable travis-buddy
  .travis.yml
Labels: process/pending review, size/XS

#147 main.html: Add fork me github corner
  templates/main.html
Labels: area/ui, difficulty/newcomer, process/pending review, size/XS
